### ISSUE TITLE
does not work on iPad

### ISSUE THREAD

**Issue by luckychris** [Ramotion/cardslider#15]
I tried the demo on iPad, but there are size issues...cells and collectionview are far too small

**Comment by musa-almatri** [comment]
its an issue with iOS 13 & Xcode 11 that changed the default modalPresentationStyle

change it to fullScreen and it will work

		let cardSlider = CardSliderViewController.with(dataSource: self)
		cardSlider.title = "Movies"
		cardSlider.modalPresentationStyle = .fullScreen

		present(cardSlider, animated: true, completion: nil)
