### ISSUE TITLE
example keeps crashing

### ISSUE THREAD

**Issue by arinasawa** [Ramotion/cardslider#9]
I tried running the example project that you guys provide and it always results in a crash. I also tried using the pod in my personal projects and it resulted in a crash. Can you guys look into it for a bug..?

**Comment by 0ber** [comment]
@arinasawa Hi, could you show crash logs or explain the steps to reproduce the crash. I checked in the demo project it works.

**Comment by igork-ramotion** [comment]
@arinasawa Hi!) If it is still actual for you please provide more details and reopen issue
